// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt2PZ5tNhaxORU7hmpnW-78G6kzBSa8yk',
    appId: '1:678560053883:web:91d545ceb7c1bf746d40de',
    messagingSenderId: '678560053883',
    projectId: 'together-app-vachira',
    authDomain: 'together-app-vachira.firebaseapp.com',
    storageBucket: 'together-app-vachira.firebasestorage.app',
    measurementId: 'G-47B9L5K18D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt0H-fdBn1bzEUP0M30iRXcVjsT22-dnQ',
    appId: '1:678560053883:android:c47abb3a89b2d0226d40de',
    messagingSenderId: '678560053883',
    projectId: 'together-app-vachira',
    storageBucket: 'together-app-vachira.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0EtkmiW6f-iHuWdOAQuuH0XgaKHW7GsM',
    appId: '1:678560053883:ios:35bbdc5e1ab40bbe6d40de',
    messagingSenderId: '678560053883',
    projectId: 'together-app-vachira',
    storageBucket: 'together-app-vachira.firebasestorage.app',
    iosBundleId: 'com.example.together',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0EtkmiW6f-iHuWdOAQuuH0XgaKHW7GsM',
    appId: '1:678560053883:ios:35bbdc5e1ab40bbe6d40de',
    messagingSenderId: '678560053883',
    projectId: 'together-app-vachira',
    storageBucket: 'together-app-vachira.firebasestorage.app',
    iosBundleId: 'com.example.together',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt2PZ5tNhaxORU7hmpnW-78G6kzBSa8yk',
    appId: '1:678560053883:web:d3a1a4d018d28a626d40de',
    messagingSenderId: '678560053883',
    projectId: 'together-app-vachira',
    authDomain: 'together-app-vachira.firebaseapp.com',
    storageBucket: 'together-app-vachira.firebasestorage.app',
    measurementId: 'G-53PY51D9XP',
  );

}